server:
  port: 80
  servlet:
    context-path: /Client
spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/swd_v2
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
    
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher